<a href="https://colab.research.google.com/github/11daniel/AIPND-2022/blob/main/6th_Connect_Session_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is one of fundemental libraries to perform quantitative analysis. As the name stands Numerical Python(NumPy), it allows for extremely fast data generation and its handling.
Numpy uses the data structure array similar to python array, to store data but it much more efficient than traditional python array and list.

Its a very big lirary to learn and have many in built functions. We will cover the most often used functions when working with quantitative data.

In [ ]:
!pip install numpy

In [ ]:
# importing the numpy library as np as per convention
import numpy as np

## Numpy arrays

Numpy arrays comes in two flavours
1. Vectors- These are one dimensional arrays normally a list and is generally used to store data of similar types. E.g, Storing name of superh
2. Matrix - These analogy comes from mathmatical representation of storing array of 2 or more dimensions. However, matrix can have one row and one column too just like vectors.

In [ ]:
# creating a numpy array

marks_list = [45,52,78,89,95]

# we will cast the above python list to numpy array
marks_array = np.array(marks_list)
print(marks_array)
type(marks_array)

[45 52 78 89 95]


numpy.ndarray

In [ ]:
marks_array.shape

(5,)

In [ ]:
marks_array.dtype

dtype('int64')

In [ ]:
# We can verify our claims using the type function
# checking the type of marks_list
type(marks_list)

list

In [ ]:
# checking the type of marks_array
type(marks_array)

numpy.ndarray

We can clearly see from the above type conversion that the type of numpy error gives numpy ndarray object.

To create a 2-D matrix we can create a 2D list and convert it to numpy array

In [ ]:
# we have created 3-D array of marks of three student in 5 different subjects
student_marks = [
                  [
                    [52,78,69,45,89], # student 1 marks
                    [65,89,78,98,65], # student 2 marks
                    [56,98,87,89,56], # student 3 marks
                  ],
                  [
                    [52,78,69,45,89], # student 1 marks
                    [65,89,78,98,65], # student 2 marks
                    [56,98,87,89,56], # student 3 marks
                  ]
                 ]

student_array = np.array(student_marks)


In [ ]:
student_array

array([[[52, 78, 69, 45, 89],
        [65, 89, 78, 98, 65],
        [56, 98, 87, 89, 56]],

       [[52, 78, 69, 45, 89],
        [65, 89, 78, 98, 65],
        [56, 98, 87, 89, 56]]])

Let's check the dimensions of the above list and array. Numpy have special attribute name as shape which helps to determine the dimension of numpy array.

In [ ]:
# We will use shape attribute to know student_array dimension
print(student_array.shape)
# student_array

(2, 3, 5)


In above student_array we found that numpy is smart enough to recognize that we have passed an matrix of 3 rows and 5 columns which is proved by shape (3,5) when we print the shape of array.

**arange() Function Numpy**

Just like range() function in python we can generate numpy array using arange()

In [ ]:
# using range function to create a list starting from 0 to 4
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# similarly we can create numpy array using arange()
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# You can observe that we have used a third parameter which is 2, and states the
# step size, to print the odd numbers between 1 and 10
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
# Similarly, we can print odd numbers using arange() for numpy array
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# TODO: In this coding block create a python list and numpy array displaying
# the even numbers between 0 to 10
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Note**: You cannot create 2D array using arange() function

**zeros() and one() function in numpy**

In many applications it is requrired to create zeroes and ones function as they help in matrix transformation. For example, you want to get the original matrix, you can mulitply it with numpy ones matrix or you can add it with numpy zeros matrix.

In [ ]:
# creating a 1D zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5).dtype

dtype('float64')

In the above output you ovserve there is a dot in place of every 0.
This is because, numpy assumes that these are float variables instead of integers. To verify our claim.

In [ ]:
# We are trying to get the type of 0.
type(0.)

int

In [ ]:
# We are trying to get the type of 0
type(0)

int

As you can see in the above example we can see that the type of 0. is float, wheras the type of 0 is integer.
The zeros and one functions have dtype parameter where you can specify, the type of data that you want.

In [ ]:
# To get the int value instead of default float
# we used the np int data type

print(np.zeros(5, dtype=int).dtype)
np.zeros(5, dtype=int)

int64


array([0, 0, 0, 0, 0])

In [ ]:
# The input to the zeros function is shape parameter, which is the dimension of
# matrix that we want to create
np.zeros((2,4))
# accepts a tuple parameter shape and create a matrix with 2 rows and 2 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Similarly we can create ones matrix
np.ones(5) # create a 1-D matrix

array([1., 1., 1., 1., 1.])

In [ ]:
# creates a 2-D matrix with 2 rows and 2 columns
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# TODO: 1. Create zeros and one arrays of 2,3 dimensions
# TODO: 2. Change the dtype of above created array to int and bool type
np.ones((2,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

**linpace() function**

To get a linearly spread array we can use linspace() function. Unlike arange() function, linspace() can take a start, stop and num variable that returns evenly space array.

In [ ]:
# to generate a 3 linear spread array between 0 and 50
np.linspace(1,500,10)
# space between the output 0 and 25 is same to that of 25 and 50
# 25-0 = 25
# 50-25  = 25

array([  1.        ,  56.44444444, 111.88888889, 167.33333333,
       222.77777778, 278.22222222, 333.66666667, 389.11111111,
       444.55555556, 500.        ])

In [ ]:
# TODO: print the array of 3 evenly spread numbers between 0 and 10
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

**Generating Random numbers**

We can random integers using np.random.randint() function. It takes start(inclusive), stop(exclusive), size as parameter.

In [ ]:
# only start and stop provided will print any number between 0 and 10
np.random.randint(0,10)

5

In [ ]:
# will print 5 random numbers between 0 and 10
np.random.randint(0,10,5)

array([7, 0, 3, 3, 5])

In [ ]:
# TODO: run the above cells multiple times to generate different numbers

**reshape() your array**

We have requirements sometimes to reshape the array during matrix computaion like matrix multiplication. We can use reshape() function to reshape our array. The reshape() function takes shape as argument, to change the dimensions of array.


In [ ]:
# creating a 1-D array of first 25 numbers
first_25 = np.arange(1,26)
first_25

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
# suppose we want to change the function into matrix of 5 rows and 5 columns
first_25.reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Note: You cannot use the reshape function to generate different size array, As you can see below that we get ValueError when we try to reshape a array of size 25(elements) to a matrix which have size 20 (5*4). Where 5 is the rows and 4 is the column.

In [ ]:
first_25.reshape(1,5,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]])

In [ ]:
# TODO: create a 1-D array of 10 random elements and reshape it to 5,2 and 2,5 matrix
# Try to reshape it into 2,2 and 4,2 matrix and see if you are successful.


## Numpy Operations & Indexing

We can perform various numeric and conditional operation on numpy array. Numpy supports broadcasting, where we numeric operation can be performed on arrays of different shapes

In [ ]:
broad_arr = np.arange(0,10)
broad_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# suppose we want to add 5 to each element of broad_arr
broad_arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# similarly we can perform other operations
# performing exponential operation
broad_arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
broad_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Numpy Indexing**

Just like python list we can perform indexing operation to select certain values from numpy array. We can use slicing notation(:) to grab the values of certain elements of numpy array.


In [ ]:
# creating a array from 0 to 9
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# To select any element of array, we will pass the index that we want
arr[0]

0

In [ ]:
# using silicing to get values from 1 to 4
# Note that 1 is the starting index which will be included and,
# 5 will be the end index which wil be excluded
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
# If we want every element upto a certain position
# this will not include 5 index
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
# If we want every element after a certain element
# we want every element after 2nd index
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# If we wan't to use broadcasting to change a certian values
# Changing first 5 values to 25
arr[:5] = 25

In [ ]:
# Note that the changes are permanent after broadcasting
arr

array([25, 25, 25, 25, 25,  5,  6,  7,  8,  9])

In [ ]:
# reassigning array
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# TODO grab the elements from 5 index to last element
# Grab the last 3 elements of above array
arr[-3:]

array([7, 8, 9])

**Conditional Selection**

Numpy provides flexibility to perform conditional selection which is very important feature. Let's see this property with help of a new example

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# suppose we want to know what are elements which are greater than 4
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In the above example we did broadcasting to check which elements contains value greater than 4. We get an boolean array having True value after 5th index. For rest of the array where value is less than or equal to 4 the value returned False.

In [ ]:
# Now we can use the bool_arr to get the values which are greater than 4,
# from original array
arr[arr > 4]

array([5, 6, 7, 8, 9])

In [ ]:
# We can perform the operation directly on arr
arr[(arr > 4) | (arr<8)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# TODO : Use conditional selection to get all values less than 6
# Use conditional selection to get all values equal to 10
# arr[(arr<6)]
arr[arr == 8]

array([8])

# Exercise
There are two choclate companies, they generated their FY 2020 and 2021 quaterly revenue. As a data analyst, you have to identify the organization which made more profit in FY 2021

1.   Construct a numpy array from revenue list for Company A in FY 2020[20,40,40,50]
2.   Write code to get the quarter with max revenue for compnay A.
3.   Competition company B with revenue quarter list in FY 2020[30,40,50,60]
4.   Company A grew by 2X profit for each quarter in FY 2021
5.   Company B grew by 1.5X profit for each quarter in FY 2021
6.   Compare total profit of both companies for FY 2021 and difference by which one company outperform the other compnay
7.   Mean profit comparision of both company in FY 2021  







# Task
Analyze the quarterly revenue data for two chocolate companies, Company A and Company B. First, create NumPy arrays for Company A's FY 2020 revenue (20, 40, 40, 50) and Company B's FY 2020 revenue (30, 40, 50, 60). Then, determine the quarter with the maximum revenue for Company A in FY 2020. Next, calculate Company A's FY 2021 revenue by multiplying each FY 2020 quarter's revenue by 2, and Company B's FY 2021 revenue by multiplying each FY 2020 quarter's revenue by 1.5. Finally, compare the total and mean profits for both companies in FY 2021, calculate the difference in total profit, and provide a summary of which company outperformed the other.

## Construct Company A FY2020 Revenue

### Subtask:
Construct a NumPy array for Company A's FY 2020 quarterly revenue using the provided list [20, 40, 40, 50].


**Reasoning**:
To construct the NumPy array for Company A's FY 2020 quarterly revenue, I will first create a Python list with the given values and then convert it into a NumPy array.



In [ ]:
company_a_fy2020_revenue_list = [20, 40, 40, 50]
company_a_fy2020_revenue = np.array(company_a_fy2020_revenue_list)

print("Company A FY 2020 Revenue List:", company_a_fy2020_revenue_list)
print("Company A FY 2020 Revenue Array:", company_a_fy2020_revenue)

Company A FY 2020 Revenue List: [20, 40, 40, 50]
Company A FY 2020 Revenue Array: [20 40 40 50]


## Find Max Revenue Quarter for Company A

### Subtask:
Identify and display the quarter with the maximum revenue for Company A in FY 2020.


**Reasoning**:
To identify the quarter with the maximum revenue, I will use NumPy's `max()` method to find the highest revenue value and `argmax()` to get its index. Since quarters are 1-indexed, I will add 1 to the index to display the correct quarter number.



In [ ]:
max_revenue_a = company_a_fy2020_revenue.max()
max_revenue_quarter_index_a = company_a_fy2020_revenue.argmax()
max_revenue_quarter_a = max_revenue_quarter_index_a + 1

print(f"Company A FY 2020 Max Revenue: {max_revenue_a}")
print(f"Company A FY 2020 Max Revenue Quarter: Quarter {max_revenue_quarter_a}")

Company A FY 2020 Max Revenue: 50
Company A FY 2020 Max Revenue Quarter: Quarter 4


## Construct Company B FY2020 Revenue

### Subtask:
Construct a NumPy array for Company B's FY 2020 quarterly revenue using the provided list [30, 40, 50, 60].

**Reasoning**:
To construct the NumPy array for Company B's FY 2020 quarterly revenue, I will first create a Python list with the given values and then convert it into a NumPy array.



In [ ]:
company_b_fy2020_revenue_list = [30, 40, 50, 60]
company_b_fy2020_revenue = np.array(company_b_fy2020_revenue_list)

print("Company B FY 2020 Revenue List:", company_b_fy2020_revenue_list)
print("Company B FY 2020 Revenue Array:", company_b_fy2020_revenue)

Company B FY 2020 Revenue List: [30, 40, 50, 60]
Company B FY 2020 Revenue Array: [30 40 50 60]


## Calculate Company A FY2021 Revenue

### Subtask:
Calculate Company A's FY 2021 revenue by multiplying each FY 2020 quarter's revenue by 2.

**Reasoning**:
To calculate Company A's FY 2021 revenue, I will multiply the `company_a_fy2020_revenue` NumPy array by 2, as per the subtask instructions, and store it in a new variable `company_a_fy2021_revenue`.



In [ ]:
company_a_fy2021_revenue = company_a_fy2020_revenue * 2

print("Company A FY 2020 Revenue:", company_a_fy2020_revenue)
print("Company A FY 2021 Revenue:", company_a_fy2021_revenue)